name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: go-fmt
        run: make fmt

      - name: go-lint
        uses: docker://morphy/revive-action:v2

        # Run build of the application
      - name: Run build
        run: go build .

      - name: Build
        run: go build -v ./...
